language: node_js
node_js:
  - node
script:
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
  - node npm-publish.js
  - cd dist.npm
  - fi
deploy:
  edge: true
  provider: npm
  email: "fabien.levavasseur@gmail.com"
  api_key: $NPM_AUTH_TOKEN
  skip_cleanup: true
  on:
    tags: true